VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	# General Vagrant VM configuration
	config.vm.box = "geerlingguy/centos7"
	config.ssh.insert_key = false
	config.vm.synced_folder ".", "/vagrant", disabled: true
	
	config.vm.define "web" do |app|
		app.vm.hostname = "web.test"
		app.vm.network :private_network, ip: "192.168.60.4"
	end

end